### ISSUE TITLE
ERROR at line 1: Unknown command '\`'. with undefined database

### ISSUE THREAD

**Issue by stalinkay** [timkelty/shipit-db#22]
Hi,

I'm having trouble pulling a MySQL database using ships-db, please help. I have used it successfully in the past without any problems. This is a new problem. The database name is not getting resolved from my shipitfile configuration on my local machine. Everything appears to be fine on the remote machine, the database is copied successfully.

I'm running macOS Sierra 10.12.4 with ShipIt v3.0.0,ShipIt Deploy v2.4.0 and ShipIt DB v1.8.3.

*Terminal Output*
```
Running "rm -f ~/public_html/shared/db/example_201604041410_dev-20170306134257.sql.bz2" on host "example.com".
Running "bunzip2 -f /tmp/example-website/db/example_201604041410_dev-20170306134257.sql.bz2 && mysql  --execute 'CREATE DATABASE IF NOT EXISTS \`undefined\`;' && mysql  -D undefined < /tmp/example-website/db/example_201604041410_dev-20170306134257.sql" on local.
@ ERROR at line 1: Unknown command '\`'.
'db:pull:task' errored after 21 s
Error: Command failed: bunzip2 -f /tmp/example-website/db/example_201604041410_dev-20170306134257.sql.bz2 && mysql  --execute 'CREATE DATABASE IF NOT EXISTS \`undefined\`;' && mysql  -D undefined < /tmp/example-website/db/example_201604041410_dev-20170306134257.sql
ERROR at line 1: Unknown command '\`'.

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:484:12)
```

*shipitfile.js*
```
module.exports = function (shipit) {
  require('shipit-deploy')(shipit);
  require('shipit-db')(shipit);

  shipit.initConfig({
    default: {
      workspace: '/tmp/example-website',
      deployTo: '~/public_html',
      repositoryUrl: 'git@github.com:example/example-website.git',
      ignores: ['.git', 'node_modules', './*.js'],
      rsync: ['--del'],
      keepReleases: 1,
      key: '~/.ssh/id_rsa',
      shallowClone: true,
      branch: 'master',
      db: {
       ignoreTables: ['some_table'],
       local: {
         host     : 'localhost',
         adapter  : 'mysql',
         username : 'root',
         password : 'root',
         socket   : '/Applications/MAMP/tmp/mysql/mysql.sock',
         database : 'example',
       }
     }
    },
    staging: {
      servers: 'example@example.com',
      branch: 'master',
      db: {
        remote: {
          host     : '127.0.0.1',
          adapter  : 'mysql',
          username : 'exampleadmin',
          password : 'Exampl3passw0rd!',
          database : 'example_201604041410_dev',
        }
      }
    },
    template: {
      workspace: '/tmp/example-website/template',
      servers: 'example@example.com',
      branch: 'master',
      deployTo: '~/public_html/templates/example',
      repositoryUrl: 'git@github.com:example/example-template.git',
      db: {
        remote: {
          host     : '127.0.0.1',
          adapter  : 'mysql',
          username : 'exampleadmin',
          password : 'Exampl3passw0rd!',
          database : 'example_201604041410_dev',
        }
      }
    }
  });

	function unpackDeployment() {
		var cmd = [];

		shipit.deployTime = moment().utc().format( 'YYYYMMDDHHmmss' );

		cmd.push( 'cd ' + shipit.deployPath );
		cmd.push( 'unzip -q ' + shipit.archiveFile );
		cmd.push( 'mv ' + package.name + ' ' + shipit.deployTime );
		cmd.push( 'rm ' + shipit.archiveFile );

		return shipit.remote( cmd.join( ' && ' ) );
	}

	function updateSymlink() {
		var cmd = [];

		cmd.push( 'cd ' + shipit.config.publicPath );
		cmd.push( 'ln -sn ' + shipit.deployPath + shipit.deployTime + ' ' + package.name + '-temp' );
		cmd.push( 'mv -T ' + package.name + '-temp ' + package.name );

		return shipit.remote( cmd.join( ' && ' ) );
	}

	function cleanOldReleases() {
		var cmd = '';

		cmd += '(';
			cmd += 'ls -rd ' + shipit.deployPath + '*|head -n 5;';
			cmd += 'ls -d ' + shipit.deployPath + '*';
		cmd += ')';
		cmd += '|sort|uniq -u|xargs rm -rf';

		return shipit.remote( cmd );
	}

};
```

**Comment by timkelty** [comment]
There seems to be some issues with the recently rolled-in backtick escaping for databases with hyphens in the name.

If you roll back to `1.8.1` it should work again.
I'll look into fixing this shortly.

**Comment by stalinkay** [comment]
@timkelty Thank you for your reply. I'm still getting the same error with `1.8.1` although the message is slightly different. The database name seems to always be undefined.

```
Running "bunzip2 -f /tmp/example-website/db/example_201604041410_dev-20170306175010.sql.bz2 && mysql  --execute "CREATE DATABASE IF NOT EXISTS undefined;" && mysql  -D undefined < /tmp/example-website/db/example_201604041410_dev-20170306175010.sql" on local.
@ ERROR 1044 (42000) at line 1: Access denied for user ''@'localhost' to database 'undefined'
'db:pull:task' errored after 21 s
Error: Command failed: bunzip2 -f /tmp/example-website/db/example_201604041410_dev-20170306175010.sql.bz2 && mysql  --execute "CREATE DATABASE IF NOT EXISTS undefined;" && mysql  -D undefined < /tmp/example-website/db/example_201604041410_dev-20170306175010.sql
ERROR 1044 (42000) at line 1: Access denied for user ''@'localhost' to database 'undefined'

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

**Comment by timkelty** [comment]
@stalinkay I just published `1.8.5`, can you give that a shot?

**Comment by dkouvdis** [comment]
I have the same issue. Relating to this [comment](https://github.com/timkelty/shipit-db/issues/22#issuecomment-284490596)

After detecting for a while, seems that when the script runs the mysql command - it cannot pick the local config. Even not picking up the username `root`

Remote config works fine.

```
db: {
    local: {
          host: 'localhost',
          adapter: 'mysql',
          username: 'root',
          password: 'root',
          database: 'whatever_db',
          socket: '/Applications/MAMP/tmp/mysql/mysql.sock',
    }
}
```

**Comment by bryantAXS** [comment]
I'm having the same issue here.

**Comment by stalinkay** [comment]
@timkelty I'm still getting the same error. As pointed out @dkouvdis the local configuration is not being detected. I suspect it could also be specific to newer versions of macOS. I'm running macOS Sierra with MAMP installed and linking to its mysql.

```ERROR 1044 (42000) at line 1: Access denied for user ''@'localhost' to database 'undefined'```

**Comment by M-jerez** [comment]
I've installed 1.8.5 and solved the issue for me!

**Comment by dkouvdis** [comment]
@M-jerez I am assuming you already had default user pre-set to localhost? I am on `1.8.5`. Try removing the user value from your local config - if it still works, you have a different setup

**Comment by M-jerez** [comment]
@dkouvdis  you are right, I've removed my prev comment avoid any confusion.

**Comment by rohullahkhalid** [comment]
I have the same issue with uploading database of sql server to plesk. there may be compatibility issue or something else, i dont know.

**Comment by Khalid111392** [comment]
Hello, I have compatibility issue when I try to import dump, it gives me the error Unable to import the marketaf_DB dump:
Unable to restore database 'marketaf_DB'
ERROR at line 1: Unknown command '\ÿ'.
(Error code 22)

**Comment by cquinders** [comment]
I’m having the same issue here. I looked into the various parts and think it comes down to this: `shipit-db` looks for db configs in `shipit.config.db[environment]`. If I run `shipit production db:push` in Terminal, `shipit-db` will read the `local` and `production` props from `shipit.config.db`. `production` is defined but `local` is not. 

I think this has to do with some recent changes in how `shipit-cli` composes the `config` object described here: https://github.com/shipitjs/shipit/issues/93.

I suppose `shipit-db` needs to adapt to the recent changes with environment configs in `shipit-cli`?
